algoritmo "SomaFuncao"
// Função :
// Autor :
// Data : 11/21/2020
// Seção de Declarações 
var
   V1, V2, S: Inteiro
   
 funcao soma(x, y: inteiro): inteiro
 Inicio
       Retorne X + Y
 Fimfuncao
   
   
inicio
// Seção de Comandos 
   Escreval("digite o primeiro valor:")
   Leia(v1)
   Escreval("digite o segundo valor: ")
   Leia(v2)
   S <- soma(v1, v2)
   EscrevaL("a soma entre", V1, " e ", v2, " é igual a ", S)


fimalgoritmo
