algoritmo "SomaParametrosReferencia"
// Função :
// Autor :
// Data : 11/21/2020
// Seção de Declarações 
var
   X, Y: Inteiro

Procedimento Soma (var A, B: Inteiro)
Inicio
      A <- A + 1
      B <- B + 2
      Escreval("valor de A = ", A)
      Escreval("valor de B = ", B)
      EscrevaL("valor de A + B = ", A+B)
FimProcedimento

Inicio
      X <- 4
      Y <- 8
      Soma (x, Y)
      Escreval("valor de X = ", X)
      Escreval("valor de Y = ", Y)

fimalgoritmo
