algoritmo "Creuza05"
// Função :
// Autor :
// Data : 11/14/2020
// Seção de Declarações
var
    parcelas: Inteiro
    emprestimo, valor: Real

inicio
// Seção de Comandos
         Escreva("Qual o valor do empréstimo? ")
         Leia (emprestimo)
         Escreva("Quantas parcelas? ")
         Leia (parcelas)
         Valor <- (emprestimo*1.20/parcelas)
         Escreva("Eu vou pagar", parcelas," parcelas de R$", valor)
         
         
         


fimalgoritmo
